obj-$(CONFIG_SENSORS)		+= sensors_class.o
obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o

obj-$(CONFIG_RAON_REMOTE_CTRL_SOC) += remote/

# YL sensor marco @yinchao
obj-$(CONFIG_YL_SENSORS_PARAMS)  += sensparams/
obj-$(CONFIG_YL_SENSORS_ALSPROX) += alsprox/
obj-$(CONFIG_YL_SENSORS_GSENSOR) += accel/
obj-$(CONFIG_YL_SENSORS_HALL)    += hall/
obj-$(CONFIG_YL_SENSORS_MAG)     += magnetometer/
obj-$(CONFIG_YL_SENSORS_LSM6DS3) += lsm6ds3/
