############################################
## 	Makefile for acc sensors devices 			
## 	Author:LongJiang 									
## 	Date:2013-09-13 									
############################################

# Each configuration option enables a list of files.

obj-$(CONFIG_YL_N2DM_GSENSOR)   += n2dm/
