#
# Makefile for the kernel dual port ram.
#

obj-$(CONFIG_YULONG_DEBUG)				+= yl_debug.o
obj-$(CONFIG_ANDROID_DEV_DEBUG)			+= android_dev_debug.o
obj-$(CONFIG_YULONG_MODULE_MANAGEMENT)	+= yulong_module_management.o
obj-$(CONFIG_YULONG_USB_UART_SWITCH)	+= usb_uart_switch.o
obj-y									+= yl_phone_mode.o
