#drivers/input/touchscreen/focaltech_touch
#
#Makefile for flash module
#
	
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_global.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft5x06.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft5x36.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft6x06.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft6x36.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft5822.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft8606.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft8707.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V1D3D3) += focaltech_flash_ft8736.o

