#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

: Nothing
GIT_BRANCH=`cat .git/HEAD | sed "s/ref: refs\/heads\///"`
CONFIG_FILE=`pwd`/scripts/set_env.txt$GIT_BRANCH
scripts/commit-to-yulong.sh HEAD $CONFIG_FILE
