#include <linux/pinctrl/pinconf-generic.h>

struct gpio_configs{
	unsigned gpio;
	char *name;
	bool reconfig_func;
	unsigned int func;
	bool reconfig_config;
	unsigned long suspend;
	unsigned long active;
};

static struct gpio_configs act_sus_configs[] = {
{.gpio = 0, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = true, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_PULL_DOWN},	
{.gpio = 1, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},
{.gpio = 2, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 3, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 4, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 5, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 6, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 7, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 8, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 9, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 10, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = true, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_DISABLE},	
{.gpio = 11, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 12, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 13, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 14, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 15, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 16, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 17, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 18, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 19, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 20, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 21, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 22, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 23, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 24, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 25, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 26, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = true, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_DISABLE},	
{.gpio = 27, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 28, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 29, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 30, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 31, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 32, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 33, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 34, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = true, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_DISABLE},	
{.gpio = 35, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 36, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 37, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 38, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = true, .suspend = PIN_CONFIG_BIAS_PULL_UP, .active = PIN_CONFIG_BIAS_PULL_UP},	
{.gpio = 39, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 40, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 41, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 42, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 43, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 44, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 45, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 46, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 47, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 48, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 49, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 50, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 51, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 52, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 53, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 54, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 55, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 56, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 57, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 58, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 59, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 60, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 61, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 62, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 63, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 64, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 65, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 66, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 67, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 68, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 69, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 70, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 71, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 72, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 73, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 74, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 75, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 76, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 77, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 78, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 79, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 80, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 81, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 82, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 83, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 84, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 85, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 86, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 87, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 88, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 89, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 90, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 91, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 92, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 93, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 94, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 95, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 96, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 97, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 98, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 99, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 100, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 101, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 102, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 103, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 104, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 105, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 106, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 107, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 108, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_PULL_DOWN},	
{.gpio = 109, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = PIN_CONFIG_BIAS_PULL_DOWN, .active = PIN_CONFIG_BIAS_PULL_DOWN},	
{.gpio = 110, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 111, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 112, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 113, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 114, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 115, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 116, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 117, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 118, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 119, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 120, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 121, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 122, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 123, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 124, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 125, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 126, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 127, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 128, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 129, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 130, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 131, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 132, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 133, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 134, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
{.gpio = 135, .name = "noname", .reconfig_func = 0, .func = 0, .reconfig_config = 0, .suspend = 0, .active = 0},	
};

